config/routes.rb
Darlo::Application.routes.draw do

  resources :adjectives

  resources :factions

  resources :characters

  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show,:index]
  match 'users/:id/change_role' => 'users#change_role', :as => 'change_role_path'

end

app/models/adjective.rb
class Adjective
  include Mongoid::Document

  validates_uniqueness_of :word

  field :word
  field :type
  field :bias, :default => "Positive"
end

app/controllers/adjectives_controller.rb
class AdjectivesController < ApplicationController
    before_filter :authenticate_user!
  # GET /adjectives
  # GET /adjectives.xml
  def index
    @adjectives = Adjective.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @adjectives }
    end
  end

  # GET /adjectives/1
  # GET /adjectives/1.xml
  def show
    @adjective = Adjective.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @adjective }
    end
  end

  # GET /adjectives/new
  # GET /adjectives/new.xml
  def new
    @adjective = Adjective.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @adjective }
    end
  end

  # GET /adjectives/1/edit
  def edit
    @adjective = Adjective.find(params[:id])
  end

  # POST /adjectives
  # POST /adjectives.xml
  def create
    @adjective = Adjective.new(params[:adjective])

    respond_to do |format|
      if @adjective.save
        format.html { redirect_to(@adjective, :notice => 'Adjective was successfully created.') }
        format.xml  { render :xml => @adjective, :status => :created, :location => @adjective }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @adjective.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /adjectives/1
  # PUT /adjectives/1.xml
  def update
    @adjective = Adjective.find(params[:id])

    respond_to do |format|
      if @adjective.update_attributes(params[:adjective])
        format.html { redirect_to(@adjective, :notice => 'Adjective was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @adjective.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /adjectives/1
  # DELETE /adjectives/1.xml
  def destroy
    @adjective = Adjective.find(params[:id])
    @adjective.destroy

    respond_to do |format|
      format.html { redirect_to(adjectives_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/adjectives_helper.rb
module AdjectivesHelper
end

app/views/adjectives/_form.html.haml
= semantic_form_for @adjective do |form|
  = form.inputs do
    = form.input :word, :hint => " The actual word"
    = form.input :type, :collection => ["Physical", "Psychological", "Persona"]
    = form.input :bias, :collection => ["Positive", "Negative"]

    = form.buttons do
      = form.commit_button

app/views/adjectives/edit.html.haml
%h1 Editing adjective

= render 'form'

= link_to 'Show', @adjective
\|
= link_to 'Back', adjectives_path

app/views/adjectives/index.html.haml
%h1 Listing adjectives

%table
  %tr
    %th Word
    %th Type
    %th Bias
    %th
    %th
    %th

  - @adjectives.each do |adjective|
    %tr
      %td= adjective.word
      %td= adjective.type
      %td= adjective.bias
      %td= link_to 'Show', adjective
      %td= link_to 'Edit', edit_adjective_path(adjective)
      %td= link_to 'Destroy', adjective, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Adjective', new_adjective_path

app/views/adjectives/new.html.haml
%h1 New adjective

= render 'form'

= link_to 'Back', adjectives_path

app/views/adjectives/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_adjective_path(@adjective)
\|
= link_to 'Back', adjectives_path