config/routes.rb
Darlo::Application.routes.draw do

  resources :adjectives

  resources :factions

  resources :characters

  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show,:index]
  match 'users/:id/change_role' => 'users#change_role', :as => 'change_role_path'

end

app/controllers/factions_controller.rb
class FactionsController < ApplicationController
  # GET /factions
  # GET /factions.xml
  def index
    @factions = Faction.all.order_by([:name, :asc])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @factions }
    end
  end

  # GET /factions/1
  # GET /factions/1.xml
  def show
    @faction = Faction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @faction }
    end
  end

  # GET /factions/new
  # GET /factions/new.xml
  def new
    @faction = Faction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @faction }
    end
  end

  # GET /factions/1/edit
  def edit
    @faction = Faction.find(params[:id])
  end

  # POST /factions
  # POST /factions.xml
  def create
    @faction = Faction.new(params[:faction])

    respond_to do |format|
      if @faction.save
        format.html { redirect_to(factions_url, :notice => 'Faction was successfully created.') }
        format.xml  { render :xml => @factions, :status => :created, :location => @faction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @faction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /factions/1
  # PUT /factions/1.xml
  def update
    @faction = Faction.find(params[:id])

    respond_to do |format|
      if @faction.update_attributes(params[:faction])
        format.html { redirect_to(factions_url, :notice => 'Faction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @faction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /factions/1
  # DELETE /factions/1.xml
  def destroy
    @faction = Faction.find(params[:id])
    @faction.destroy

    respond_to do |format|
      format.html { redirect_to(factions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/factions_helper.rb
module FactionsHelper
end

app/views/factions/_form.html.haml
= semantic_form_for @faction do |form|
  = form.inputs do
    = form.input :name, :hint => " The faction name"
    = form.input :tagcolour, :collection => ["Red", "Orange", "Yellow", "Green", "Blue", "Indigo", "Violet"], :include_blank => true
    = form.input :description, :hint => "A one line description of the faction"
    = form.input :long_description, :as => :text, :hint => ("A much more in-depth description of the faction, please use " + link_to("Markdown","http://daringfireball.net/projects/markdown/basics")).html_safe, :input_html => { :class => 'txtInput', :cols =>"120", :rows=>"2" }
    = form.input :roleplay_hints, :as => :text, :hint => ("Advice and inspiration for roleplaying the faction, Please use " + link_to("Markdown","http://daringfireball.net/projects/markdown/basics")).html_safe,:input_html => { :class => 'txtInput', :cols =>"120", :rows=>"2" }
    = form.input :image, :collection => file_array("/public/images/", "*.png"), :include_blank => true

    = form.buttons do
      = form.commit_button

app/views/factions/edit.html.haml
%h1 Editing faction

= render 'form'

= link_to 'Show', @faction
\|
= link_to 'Back', factions_path

app/views/factions/index.html.haml
- @page_title = "Factions"
%div.block
  %div.content
    %div.inner
      %h2.title Factions
      %table.table
        %tr
          %th
          %th Name
          %th Description
          %th
          %th
          %th
        - @factions.each do |faction|
          %tr{ :class=> faction.tagcolour.downcase }
            - if faction.image?
              %td=  image_tag(faction.image,:height => 60,:width => 60)
              - else
                %td No image
            %td= faction.name
            %td= faction.description
            %td= link_to 'Show', faction
            %td= link_to 'Edit', edit_faction_path(faction)
            %td= link_to 'Destroy', faction, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Faction', new_faction_path

app/views/factions/new.html.haml
%h1 New faction

= render 'form'

= link_to 'Back', factions_path

app/views/factions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @faction.name
%p
  %b Description:
  = @faction.description
%p
  %b Greeting:
  = @faction.greeting

= link_to 'Edit', edit_faction_path(@faction)
\|
= link_to 'Back', factions_path