config/routes.rb
Darlo::Application.routes.draw do

  resources :adjectives

  resources :factions

  resources :characters

  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show,:index]
  match 'users/:id/change_role' => 'users#change_role', :as => 'change_role_path'

end

app/models/character.rb
class Character
  include Mongoid::Document
  include Mongoid::Paranoia
  include Mongoid::Versioning
  include Mongoid::Timestamps
  include Mongoid::Taggable
  max_versions 5
  field :name, :type => String
  field :description, :type => String
  field :long_description, :type => String
  field :npc, :type => Boolean, :default => false
  field :gender
  field :roleplay_hints
  field :max_adjectives, :type => Integer, :default => 5
  field :played_by, :default => "No one yet"
  validates_presence_of :name
  referenced_in :user
  referenced_in :faction
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /characters
  # GET /characters.xml
  def index
    @characters = Character.order_by([:name, :asc])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.xml
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.xml
  def new
    @character = Character.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.xml
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to(@character, :notice => 'Character was successfully created.') }
        format.xml  { render :xml => @character, :status => :created, :location => @character }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @character.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.xml
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to(@character, :notice => 'Character was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @character.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.xml
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to(characters_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.haml
:javascript
  $(document).ready(function(){$(".adjectives").multiselect({
    minWidth: 625,
    selectedList: 10,
    header: "Choose #{@character.max_adjectives.to_s} adjectives",
      click: function(e){
          if( $(this).multiselect("widget").find("input:checked").length > #{@character.max_adjectives} ){
              warning.addClass("error").removeClass("success").html("You can only check checkboxes!");
              return false;
          } else {
              $(this).multiselect("widget");
              warning.addClass("success").removeClass("error").html("Check a few boxes.");
          }
      }
    });
   });

= semantic_form_for @character do |form|
  = form.inputs do
    = form.input :name, :hint => " The characters name"
    = form.input :gender, :collection => ["Male", "Female", "Other"],:input_html => { :class => 'fancyselect'}
    = form.input :description, :hint => "A brief description"
    = form.input :long_description, :as => :text, :hint => ("A much more in-depth description of the character, please use " + link_to("Markdown","http://daringfireball.net/projects/markdown/basics")).html_safe, :input_html => { :class => 'txtInput', :cols =>"120", :rows=>"2" }
    = form.input :tags_array, :label => "Adjectives", :as => :select, :collection => list_adjectives("All","Positive") , :hint => "The characters adjectives", :input_html => { :multiple => true , :class => 'adjectives', :wrapper_html => { :style => "width: 700px;" }}
    = form.input :faction_id, :collection => Faction.asc(:name), :label => "Faction",:input_html => { :class => 'fancyselect'}
    = form.input :roleplay_hints, :as => :text, :hint => ("Advice and inspiration for roleplaying the character, Please use " + link_to("Markdown","http://daringfireball.net/projects/markdown/basics")).html_safe,:input_html => { :class => 'txtInput', :cols =>"120", :rows=>"2" }
    - if current_user.role? :helper
      = form.input :npc, :as => :boolean
      = form.input :played_by, :as => :select, :collection => list_users,:input_html => { :class => 'fancyselect'}

      = form.input :user_id, :as => :select, :collection => User.asc(:name), :label => "Owner",:input_html => { :class => 'fancyselect'}
    - else
      = form.input :npc, :as => :hidden
      - if action_name == "new"
        = form.input :user_id, :as => :hidden, :value => current_user._id
    = form.buttons do
      = form.commit_button

app/views/characters/edit.html.haml
%div.content
  %h2.title Editing character
  %div.inner

    = render 'form'

    = link_to 'Show', @character
    \|
    = link_to 'Back', characters_path

app/views/characters/index.html.haml
- @page_title = "Characters"
%div.block
  %div.content
    %div.inner
      %h2.title Characters
      %table.table
        %tr
          %th Name
          %th Description
          %th Player
          %th Faction
          %th Last Updated
          %th
          %th
        - @characters.each do |character|
          - unless character.npc?
            -if can? :edit, character
              %tr
                %td= link_to character.name, character
                %td= character.description
                %td= character.user.name if character.user
                %td= character.faction.name
                %td= time_ago_in_words(character.updated_at.utc) if character.updated_at
                %td= link_to "Edit", edit_character_path(character) if can? :edit, character
                %td= link_to "Delete", character, :confirm => ('Are you sure you wish to delete ' + character.name+'?'), :method => :delete if can? :destroy, character
  -if current_user.role != "player"
    %div.counter   #{25 - @characters.excludes(:npc => true).count} character spaces remaining.
-@chrnames = []
-@characters.each do |chr|
  -@chrnames << chr.name
-if current_user.role != "player" || @chrnames.include?(current_user.name)
  %div.block
    %div.content
      %div.inner
        %h2.title NPCs
        %table.table
          %tr
            %th Name
            %th Description
            %th Faction
            %th Played By
            %th Owner
            %th Adjectives
            %th Last Updated
            %th
            %th
          -@characters.each do  |character|
            -unless character.npc == false
              -if can? :read, character
                %tr{ :class=> character.faction.tagcolour.downcase }
                  %td= link_to character.name, character
                  %td= character.description
                  %td= character.faction.name
                  %td= character.played_by
                  %td= character.user.name if character.user
                  %td= character.tags_array.count unless character.tags_array.nil?
                  %td= time_ago_in_words(character.updated_at.utc) if character.updated_at
                  %td= link_to "Edit", edit_character_path(character) if can? :edit, character
                  %td= link_to "Delete", character, :confirm => ('Are you sure you wish to delete ' + character.name+'?'), :method => :delete if can? :destroy, character

%br

-if current_user.role == "player" and current_user.characters.excludes(:npc => true).count >= 1
  %p You have enough characters!
-else
  =link_to 'New Character', new_character_path

app/views/characters/new.html.haml
%h1 New character

= render 'form'

= link_to 'Back', characters_path

app/views/characters/show.html.haml
%p#notice= notice


#block-text.block
  .content
    %h2.title #{@character.name}
    .inner
      %p.first
        %span.gray #{@character.description}
      %p
        Gender: #{@character.gender}
      %p
        :markdownsmart
          #{@character.long_description}
      -if can? :read, @character
        %p Adjectives:
        %p
          -unless @character.tags_array.nil?
            =@character.tags
            =@character.tags_array.count
        :markdownsmart
          **Roleplay Hints:**

          #{@character.roleplay_hints}
      -if can? :read, @character
        = link_to 'Edit', edit_character_path(@character)
        \|
      = link_to 'Back', characters_path