config/routes.rb
Darlo::Application.routes.draw do

  resources :adjectives

  resources :factions

  resources :characters

  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show,:index]
  match 'users/:id/change_role' => 'users#change_role', :as => 'change_role_path'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Darlo Below

    = stylesheet_link_tag :all
    = stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", "ui-lightness/jquery-ui"
    = javascript_include_tag :defaults, "jquery.autogrowtextarea.js", "jquery.multiselect"
    = csrf_meta_tag
    %body
      #container
        #header
          %h1
            %a{:href => "/"} DarloBelow > #{@page_title}
          #user-navigation
            %ul.wat-cf
              - if user_signed_in?
                %li
                  %a
                    =link_to 'Your Characters', characters_path,:class => 'logout'
                    -if current_user.role == "admin"
                      %li
                        %a
                          =link_to 'Factions', factions_path,:class => 'logout'
                      %li
                        %a
                          =link_to 'Users', users_path,:class => 'logout'
                      %li
                        %a
                          =link_to 'Adjectives', adjectives_path,:class => 'logout'
              - if user_signed_in?
                %li
                  %a
                    =link_to 'Edit account', edit_user_registration_path,:class => 'logout'
              -else
                %li
                  %a
                    -# =link_to 'Sign up', new_user_registration_path, :class => 'logout'
              -if user_signed_in?
                %li
                  %a
                    =link_to 'Logout', destroy_user_session_path, :class => 'logout'
              -else
                %li
                  %a
                    =link_to 'Login', new_user_session_path, :class => 'logout'
          #main-navigation
            %ul.wat-cf
        #wrapper.wat-cf
          .flash
            - flash.each do |type, message|
              %div{:class => "message #{type}"}
                %p= message
          #main
            = yield
            #footer
              .block
                %p
          #sidebar
            = yield :sidebar